artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rayaran1000/Datasets/raw/main/Exoplanet%20data%20-%20NASA.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Exoplanet data - NASA.csv
  data_path_transformed: artifacts/data_transformation/Exoplanet Chatbot Finetuned dataset.csv


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts\data_transformation\Exoplanet Chatbot Finetuned dataset.csv
  model_ckpt: google/gemma-2b-it
  tokenizer_ckpt: google/gemma-2b-it
  model_save_path: artifacts/model_trainer/ExoChatbot_200Steps
  tokenizer_save_path: artifacts/model_trainer/ExoChatbot_200Steps_tokenizer


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts\data_transformation\Exoplanet Chatbot Finetuned dataset.csv
  model_path: artifacts/model_trainer/ExoChatbot_200Steps
  tokenizer_path: artifacts/model_trainer/ExoChatbot_200Steps_tokenizer
  evaluation_data_path: artifacts/data_transformation/evaluation_dataset
  metric_file_name: artifacts/model_evaluation/metrics.csv


prediction_pipeline:
  finetuned_model_path: artifacts/model_trainer/ExoChatbot_200Steps
  tokenizer_path: artifacts/model_trainer/ExoChatbot_200Steps_tokenizer